name: BuildRelease

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本'
        required: false
        default: '9.9.9'
  push:
    branches:
      - master
      - rewrite

jobs:
  build:
    name: 大气层打包更新
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: 当前日期
      id: date
      run: |
        echo "date=$(date +'%YY%mm%dd')" >> $GITHUB_OUTPUT
        # ${{ steps.date.outputs.date }}

    - name: 获取版本
      id: set-version
      run: |
        # version=${{ github.event.inputs.version }}
        version=$(cat ./VERSION | python -c 'import sys, json; f=open("./src/settings.json");print(json.loads(f.read())["version"])')
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: 安装 Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: 安装依赖
      run: |
        if [ -f ./requirements.txt ]; then pip3 install -r ./requirements.txt; fi
        
    - name: Download File
      run: |
        wget –q –P ./Sigpatches.zip https://jits.cc/patches
      
    - name: 打包
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        python ./build.py -gt="$GITHUB_TOKEN" -v="v${{ steps.set-version.outputs.version }}"

    - name: 发布
      run: |
        set -x
        assets=()
        for asset in ./*.zip; do
          assets+=("-a" "$asset")
        done
        hub release create "${assets[@]}" -m "Atmosphere v${{ steps.set-version.outputs.version }}" "v${{ steps.set-version.outputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
