name: BuildRelease

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本'
        required: true
        default: '9.9.9'
  push:
    branches:
      - master
      - rewrite

jobs:
  build:
    name: 大气层打包更新
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: 当前日期
      id: date
      run: |
        echo "date=$(date +'%YY%mm%dd')" >> $GITHUB_OUTPUT
        # ${{ steps.date.outputs.date }}

    - name: 获取版本
      id: set-version
      run: |
        version=${{ github.event.inputs.version }}
        # version=$(cat ./VERSION | python -c 'import sys, json; f=open("./src/settings.json");print(json.loads(f.read())["version"])')
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: 安装 Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: 安装依赖
      run: |
        if [ -f ./requirements.txt ]; then pip3 install -r ./requirements.txt; fi
        
    - name: 打包
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        python ./build.py -gt="$GITHUB_TOKEN" -v="v${{ steps.set-version.outputs.version }}"

    - name: 发布
      run: |
        set -x
        assets=()
        for asset in ./*.zip; do
          assets+=("-a" "$asset")
        done
        echo "file=${assets[@]}" >> $GITHUB_OUTPUT
        hub release create "${assets[@]}" -m "Release v${{ steps.set-version.outputs.version }}" "${{ file }}" -t "${{ steps.set-version.outputs.version }}"
        echo $file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.set-version.outputs.version }}
        release_name: ${{ steps.set-version.outputs.version }}
        body: |
          # 更新日志
          v${{ steps.set-version.outputs.version }}
        draft: false
        prerelease: false

    # 上传到release-asset 用户就可以在release页面下载了
    - name: Uploading assets...
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # 这里是create_release步骤输出的参数
        asset_path: ./
        asset_name: $file
        asset_content_type: application/gzip
