name: BuildRelease

on:
  workflow_dispatch:
    inputs:
      version:
        description: '打包版本'
        required: true
        default: ''
  push:
    branches:
      - master
      - rewrite

jobs:
  build:
    name: 大气层打包
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: 当前日期
      id: date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        # ${{ steps.date.outputs.date }}

    - name: 获取版本
      id: set-version
      run: |
        version=${{ github.event.inputs.version }}
        # version=$(cat ./VERSION | python -c 'import sys, json; f=open("./src/settings.json");print(json.loads(f.read())["version"])')
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: 安装 Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: 安装依赖
      run: |
        if [ -f ./requirements.txt ]; then pip3 install -r ./requirements.txt; fi
        sudo apt install rename

    - name: 打包文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        python ./build.py -gt="$GITHUB_TOKEN" -v="v${{ steps.set-version.outputs.version }}"
        ls
        rename 'v9.9.9' "v${{ steps.set-version.outputs.version }}" *
        for asset in *.zip; do
          echo "$asset"
        done 
        #set -x
        #assets=()
        #for asset in *.zip; do
        #  assets+=("$asset")
        #done 
        #filePack=${assets[@]}
        # unzip -u ${assets[@]} -d switch_out
        # wget -q https://jits.cc/patches -O sigpatches.zip
        # unzip -u sigpatches.zip -d switch_out
        # rm ${assets[@]}
        # rm sigpatches.zip
        # zip -q -r "Atmosphere_v${{ steps.set-version.outputs.version }}.zip" switch_out
        # filePack='-a ./deepsea-qhq_v1.4.1.zip'
        # 发布
        # hub release create "${assets[@]}" -m "Atmosphere v${{ steps.set-version.outputs.version }}" "v${{ steps.set-version.outputs.version }}"

    - name: 发布
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        allowUpdates: true
        tag: v${{ steps.set-version.outputs.version }}
        name: Atmosphere v${{ steps.set-version.outputs.version }}
        body: |
          三件套
          （1）atmosphere
          https://github.com/Atmosphere-NX/Atmosphere
          （2）hekate_ctcaer
          https://github.com/CTCaer/hekate
          （3）Sigpatches
          https://github.com/fraxalotl/SwitchScript
          https://jits.cc/patches
        prerelease: false
        artifacts: "*.zip"

